# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Patricia Cañadas' github.io sites
author: Patricia Cañadas # Author Name
email: pcanadas15@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My projects...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pcanadas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
github_username:  pcanadas
show_downloads: false
google_analytics:

# Build settings
highlighter: rouge
#theme: minima
remote_theme: pages-themes/midnight@v0.2.0

# Default Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

